name: CI
  
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y libarchive-tools genisoimage
      - name: Build and verify
        run: sudo make check VERBOSE=1
